extend: secrets.yaml

name: Amazon.com
database: amazon.db
recipient: funnybrum@gmail.com
subject: Amazon.com
send_new: True
send_updates: True
send_deletes: False
headers:
    Host: www.amazon.com
    Connection: keep-alive
    Cache-Control: max-age=0
    Upgrade-Insecure-Requests: 1
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
    Accept-Encoding: gzip, deflate, br
    Accept-Language: en-US,en;q=0.8,bg;q=0.6
sites:
    Amazon.com:
        enabled: True
        search_urls:
            - site: Dell XPS 13 9600 Refurbished
              url: https://www.amazon.com/s/ref=nb_sb_noss_1?url=search-alias%3Daps&field-keywords=dell+xps+13+9360+refurbished&rh=i%3Aaps%2Ck%3Adell+xps+13+9360+refurbished&page={0}
            - site: Lenovo Thinkad OLED
              url: https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=lenovo+thinkpad+oled&rh=i%3Aaps%2Ck%3Alenovo+thinkpad+oled&page={0}
            - site: Samsung Gear Fit2 Refurbished
              url: https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=Samsung+Gear+Fit2+refurbished&rh=i%3Aaps%2Ck%3ASamsung+Gear+Fit2+refurbished&page={0}
        list_items_match: //div[@class="s-item-container"]
        item_attributes:
            - name: id
              match: (.//div/a/@href)[1]
              post_processor: amazon_id_extractor
            - name: link
              match: (.//div/a/@href)[1]
              post_processor: amazon_link_extractor
            - name: image
              match: (.//a/img/@src)[1]
            - name: image
              match: (.//a/div/img/@src)[1]
              validator: ^.{10,}$
            - name: price
              match: concat('< ', .//span[@aria-label]/text())
              validator: ^< \$?[\d,]+[.,]\d\d$
            - name: price
              match: concat(.//sup[@class='sx-price-currency']/text(), .//span[@class='sx-price-whole']/text(), '.', .//sup[@class='sx-price-fractional']/text())
              validator: ^\$?[\d,]+[.,]\d\d$
            - name: price
              match: .//span[@class='a-size-base a-color-base']/text()
              validator: ^\$?[\d,]+[.,]\d\d$
            - name: description
              validator: .*(9350|9360|9365|OLED|oled|Fit2|Fit 2).*
              match: .//div/a/@title
        required_properties:
              id: True  # True - show warning if missing, False - don't show warning
              link: True
              price: True
              description: False
tracked_properties:
    - price
template: config/templates/amazon.html
template_config:
  name: ""
  description: Обяви от Amazon
