extend: secrets.yaml

name: Amazon.com
database: amazon.db
recipient: funnybrum@gmail.com
subject: Amazon.com
send_new: True
send_updates: True
send_deletes: False
headers:
    User-Agent: Mozilla/5.0
sites:
    Amazon.com:
        enabled: True
        search_urls:
            - site: Dell XPS 13 9600 Refurbished
              url: https://www.amazon.com/s/ref=nb_sb_noss_1?url=search-alias%3Daps&field-keywords=dell+xps+13+9360+refurbished&rh=i%3Aaps%2Ck%3Adell+xps+13+9360+refurbished&page={0}
        list_items_match: //div[@class="s-item-container"]
        item_attributes:
            - name: id
              match: (.//div/a/@href)[1]
              post_processor: amazon_id_extractor
            - name: link
              match: (.//div/a/@href)[1]
              post_processor: amazon_link_extractor
            - name: image
              match: (div/div/div/div/div/a/img/@src)[1]
            - name: price
              match: concat(.//sup[@class='sx-price-currency']/text(), .//span[@class='sx-price-whole']/text(), '.', .//sup[@class='sx-price-fractional']/text())
            - name: description
              match: .//div/a/@title
template: config/templates/amazon.html
template_config:
  name: ""
  description: Обяви от Amazon
