extend: secrets.yaml

enabled: False
name: Mixed
database: mixed.db
recipient: funnybrum@gmail.com
subject: Amazon.com & Pazaruvaj.com
send_new: True
send_updates: True
headers:
    User-Agent: Mozilla/5.0
sites:
    Graco Milestone:
        enabled: True
        search_urls:
            - site: Graco Milestone
              url: https://www.amazon.co.uk/Graco-Milestone-All-One-Seat/dp/B00XHWL7UK
        max_pages_count: 1
        list_items_match: id('dp-container')
        item_attributes:
            - name: id
              match: normalize-space(id('titleSection')/h1/span/text())
            - name: price
              match: id('priceblock_ourprice')/text()
    Samsung Galaxy A5 2017:
        enabled: True
        search_urls:
            - site: pazaruvaj.com
              url: https://www.pazaruvaj.com/mobilni-telefoni-gsm-c3277/samsung/galaxy-a5-2017-a520f-p356387087/
        max_pages_count: 1
        list_items_match: //div[@class="row product-page-top"]
        item_attributes:
            - name: id
              match: div/h1/span[2]/text()[normalize-space()]
            - name: price
              match: div/div[@class="price"]/text()[normalize-space()]
    Samsung Galaxy A3 2017:
        enabled: True
        search_urls:
            - site: pazaruvaj.com
              url: https://www.pazaruvaj.com/mobilni-telefoni-gsm-c3277/samsung/galaxy-a3-2017-single-a320f-p356592477/
        max_pages_count: 1
        list_items_match: //div[@class="row product-page-top"]
        item_attributes:
            - name: id
              match: div/h1/span[2]/text()[normalize-space()]
            - name: price
              match: div/div[@class="price"]/text()[normalize-space()]
template_name: amazon.html
