extend: secrets.yaml

name: Amazon.com
database: amazon.db
recipient: funnybrum@gmail.com
subject: Amazon.com
send_new: True
send_updates: True
send_deletes: False
enabled: False
headers:
    Host: www.amazon.com
    Connection: keep-alive
    Cache-Control: max-age=0
    Upgrade-Insecure-Requests: 1
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
    Accept-Encoding: gzip, deflate, br
    Accept-Language: en-US,en;q=0.8,bg;q=0.6
sites:
    Amazon.com:
        enabled: True
        search_urls:
            - site: Samsung SSD 500GB, price <= 150.00
              url: https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=samsung+ssd+500gb&p_74=-15000
        list_items_match: //div[@class="s-item-container"]
        item_attributes:
            - name: id
              match: (.//div/a/@href)[1]
              post_processor: amazon_id_extractor
            - name: link
              match: (.//div/a/@href)[1]
              post_processor: amazon_link_extractor
            - name: description
              validator: .*(500|512).*
              match: .//div/a/@title
            - name: image
              match: (.//a/img/@src)[1]
            - name: image
              match: (.//a/div/img/@src)[1]
              validator: ^.{10,}$
              # Covers the "Click to see the price" case.
            - name: price
              match: concat("< ", .//a/text()[normalize-space(.)="Click for product details"]/parent::a/parent::div/span[@class="a-size-base-plus a-color-secondary a-text-strike"]/text())
              validator: ^< \$?[\d,]+[.,]\d\d$
              # Base case, just single price in one span, preceded by "sold by" div. Works on items in main list
            - name: price
              match: .//span/text()[normalize-space(.)="by"]/parent::span/../../following-sibling::div[1]/div[1]/div[1]/div[1]/a/span[@class="a-size-base a-color-base"]/text()
              validator: ^\$?[\d,]+[.,]\d\d$
              # Base case, just single price in one span, preceded by "sold by" div. For items not in the main list
            - name: price
              match: .//span/text()[normalize-space(.)="by"]/parent::span/../../following-sibling::div[1]/div[1]/a/span[@class="a-size-base a-color-base"]/text()
              validator: ^\$?[\d,]+[.,]\d\d$
              # Regular case for item with additional info - price in a sup and two spans
            - name: price
              match: concat(.//sup[@class="sx-price-currency"]/text(), .//span[@class="sx-price-whole"]/text(), ".", .//sup[@class="sx-price-fractional"]/text())
              validator: ^\$?[\d,]+[.,]\d\d$
              # Price of "More Buying Choices", works both in the main list and in the sublists
            - name: price
              match: .//span/text()[normalize-space(.)="More Buying Choices"]/parent::span/following::span[@class="a-size-base a-color-base"][1]/text()
              validator: ^\$?[\d,]+[.,]\d\d$
        required_properties:
              # List of properties that are required for valid item. If value is True - a warning is showed if the property
              # is missing. Description is first as we want to filter out non-relevant items silently.
              description: False
              id: True
              link: True
              price: True
#    Amazon.com single items:
#        enabled: False
#        max_pages_count: 1
#        search_urls:
#            - site: Samsung EVO 850 500GB
#              url: https://www.amazon.com/Samsung-2-5-Inch-Internal-MZ-75E500B-AM/dp/B01M8MF4IF?th=1
#            - site: Samsung EVO 850 500GB 2
#              url: https://www.amazon.com/Samsung-2-5-Inch-Internal-MZ-75E500B-EU/dp/B00P73B1E4/ref=sr_1_7?s=pc&ie=UTF8&qid=1511479258&sr=1-7&keywords=samsung+ssd+500GB
#            - site: Samsung PRO 850 512GB
#              url: https://www.amazon.com/Samsung-850-PRO-2-5-Inch-MZ-7KE512BW/dp/B00LF10KTO/ref=sr_1_5?s=pc&ie=UTF8&qid=1511479258&sr=1-5&keywords=samsung+ssd+500GB
#        list_items_match: //div[@id="dp-container"]
#        item_attributes:
#            - name: id
#              match: substring-after(.//a[@class="oneClickSignInLink"]/@href, "product%2F")
#            - name: link
#              match: "@site_url"
#            - name: description
#              match: .//span[@id="productTitle"]/text()
#              post_processor: trim
#            - name: image
#              match: (.//div[@id="main-image-container"]/.//img)[last()]/@data-old-hires
#            - name: price
#              match: .//span[@id="priceblock_ourprice"]/text()
#        required_properties:
#              # List of properties that are required for valid item. If value is True - a warning is showed if the property
#              # is missing. Description is first as we want to filter out non-relevant items silently.
#              description: False
#              id: True
#              link: True
#              price: True
tracked_properties:
    - price
template: config/templates/amazon.html
template_config:
  name: ""
  description: Обяви от Amazon
