extend: secrets.yaml

enabled: True
name: Properties monitor
database: natali.db
recipient:  nataly_nasteva@abv.bg
subject: Квартири в София
sites:
    Едностайни @ holmes.bg:
        enabled: False
        search_url: http://www.holmes.bg/pcgi/home.cgi?act=2&pn=2&f1=1&f38=%E3%F0%E0%E4+%D1%EE%F4%E8%FF&f42=&f39=&f40=%D1%F2%F3%E4%E5%ED%F2%F1%EA%E8+%E3%F0%E0%E4%2B%C4%FA%F0%E2%E5%ED%E8%F6%E0%2B%CC%F3%F1%E0%E3%E5%ED%E8%F6%E0%2B%CC%EB%E0%E4%EE%F1%F2+1%2B%CC%EB%E0%E4%EE%F1%F2+2%2B%CC%EB%E0%E4%EE%F1%F2+3%2B%CC%EB%E0%E4%EE%F1%F2+1%C0%2B%CC%EB%E0%E4%EE%F1%F2+4%2B%CB%EE%E7%E5%ED%E5%F6%2B%D6%E5%ED%F2%FA%F0%2B&f8=1&f28=&f29=350&f30=%EB%E2.&f26=&f27=&f31=&f32=&f33=&f34=&f43=%CE%E1%E7%E0%E2%E5%E4%E5%ED&f35=&f36=&f37=&f41=1&page={0}
        max_pages_match: //table/tr/td[@width=700]/a[position()=last()]/text()[normalize-space()]
        list_items_match: (//table[@width=956])[position()>1]
        item_attributes:
            - name: id
              match: tr/td/a/@href
            - name: image
              match: (td/a/img/@src)[1]
            - name: description
              match: (td)[2]//text()
            - name: price
              match: td/span[@class="ver20black"][1]//text()
            - name: area
              match: td/span[@class="ver15black"][1]//text()
            - name: link
              match: td/a[@class="ver15black"][1]/@href
              prefix: http://www.homes.bg/
    Тристайни @ holmes.bg:
        enabled: False
        search_url: http://www.holmes.bg/pcgi/home.cgi?act=2&pn=2&f1=1&f38=%E3%F0%E0%E4+%D1%EE%F4%E8%FF&f42=&f39=&f40=%D1%F2%F3%E4%E5%ED%F2%F1%EA%E8+%E3%F0%E0%E4%2B%C4%FA%F0%E2%E5%ED%E8%F6%E0%2B%CC%F3%F1%E0%E3%E5%ED%E8%F6%E0%2B%CC%EB%E0%E4%EE%F1%F2+1%2B%CC%EB%E0%E4%EE%F1%F2+2%2B%CC%EB%E0%E4%EE%F1%F2+3%2B%CC%EB%E0%E4%EE%F1%F2+1%C0%2B%CC%EB%E0%E4%EE%F1%F2+4%2B%CB%EE%E7%E5%ED%E5%F6%2B%D6%E5%ED%F2%FA%F0%2B&f10=1&f28=&f29=600&f30=%EB%E2.&f26=&f27=&f31=&f32=&f33=&f34=&f43=%CE%E1%E7%E0%E2%E5%E4%E5%ED&f35=&f36=&f37=&f41=1&page={0}
        max_pages_match: //table/tr/td[@width=700]/a[position()=last()]/text()[normalize-space()]
        list_items_match: (//table[@class="tableListResults"]/tr)[position()>1]
        item_attributes:
            - name: id
              match: td/a[@class="ver15black"]/@href
            - name: image
              match: (td/a/img/@src)[1]
            - name: description
              match: (td)[2]//text()
            - name: price
              match: td/span[@class="ver20black"][1]//text()
            - name: area
              match: td/span[@class="ver15black"][1]//text()
            - name: link
              match: td/a[@class="ver15black"][1]/@href
              prefix: http://www.homes.bg/
    Едностаен @ imot.bg:
        enabled: True
        search_url: http://www.imot.bg/pcgi/imot.cgi?act=3&rub=2&rub_pub_save=2&topmenu=2&actions=1&f0=77.70.77.231&f1={0}&f2=&f3=&f4=1&f7=2%7E&f28=&f29=350&f43=&f44=&f30=%EB%E2.&f26=&f27=&f41=1&f31=&f32=&f38=%E3%F0%E0%E4+%D1%EE%F4%E8%FF&f42=&f39=&f40=%D1%F2%F3%E4%E5%ED%F2%F1%EA%E8+%E3%F0%E0%E4%2B%C4%FA%F0%E2%E5%ED%E8%F6%E0%2B%CC%EB%E0%E4%EE%F1%F2+1%2B%CC%EB%E0%E4%EE%F1%F2+2%2B%CC%EB%E0%E4%EE%F1%F2+4%2B%CC%EB%E0%E4%EE%F1%F2+3%2B%CC%EB%E0%E4%EE%F1%F2+1%C0%2B%D6%E5%ED%F2%FA%F0%2B%CB%EE%E7%E5%ED%E5%F6%2B&fe3=&fe4=&f45=&f46=&f54=%CE%E1%E7%E0%E2%E5%E4%E5%ED&f33=&f34=&f35=&f36=&f37=&fe2=1
        max_pages_match: substring-after((//table/tr/td/table/tr/td/span[@class="pageNumbersInfo"])[1]//text(), "от ")
        list_items_match: //table[@width="660"][tr/td/div[@class="price"]]
        item_attributes:
            - name: id
              match: tr/td/div[@class="price"]/a/@id
            - name: image
              match: (tr/td/table/tr/td/a[@class="photoLink"]/img/@src)[1]
            - name: description
              match: (tr/td[@width="520"])//text()
            - name: price
              match: tr/td/div[@class="price"]//text()[1]
            - name: area
              match: tr/td/a[@class="lnk2"]//text()
            - name: link
              match: tr/td/a[@class="lnk2"]/@href
    Тристаен @ imot.bg:
        enabled: True
        search_url: http://www.imot.bg/pcgi/imot.cgi?act=3&rub=2&rub_pub_save=2&topmenu=2&actions=1&f0=77.70.77.231&f1={0}&f2=&f3=&f4=1&f7=4%7E&f28=&f29=600&f43=&f44=&f30=%EB%E2.&f26=&f27=&f41=1&f31=&f32=&f38=%E3%F0%E0%E4+%D1%EE%F4%E8%FF&f42=&f39=&f40=%D1%F2%F3%E4%E5%ED%F2%F1%EA%E8+%E3%F0%E0%E4%2B%C4%FA%F0%E2%E5%ED%E8%F6%E0%2B%CC%EB%E0%E4%EE%F1%F2+1%2B%CC%EB%E0%E4%EE%F1%F2+2%2B%CC%EB%E0%E4%EE%F1%F2+4%2B%CC%EB%E0%E4%EE%F1%F2+3%2B%CC%EB%E0%E4%EE%F1%F2+1%C0%2B%D6%E5%ED%F2%FA%F0%2B%CB%EE%E7%E5%ED%E5%F6%2B&fe3=&fe4=&f45=&f46=&f54=%CE%E1%E7%E0%E2%E5%E4%E5%ED&f33=&f34=&f35=&f36=&f37=&fe2=1
        max_pages_match: substring-after((//table/tr/td/table/tr/td/span[@class="pageNumbersInfo"])[1]//text(), "от ")
        list_items_match: //table[@width="660"][tr/td/div[@class="price"]]
        item_attributes:
            - name: id
              match: tr/td/div[@class="price"]/a/@id
            - name: image
              match: (tr/td/table/tr/td/a[@class="photoLink"]/img/@src)[1]
            - name: description
              match: (tr/td[@width="520"])//text()
            - name: price
              match: tr/td/div[@class="price"]//text()[1]
            - name: area
              match: tr/td/a[@class="lnk2"]//text()
            - name: link
              match: tr/td/a[@class="lnk2"]/@href
    Едностаен @ imoti.net:
        enabled: True
        search_url: http://www.imoti.net/search/results/?personal=&ad_type_id=3&save_search=1&search_form=prodajbi&lang=bg&x=56&y=19&building_type_id[]=5&price_from=&price_to=350&currency_id=2&price_kv_from=&price_kv_to=&currency_kv_id=4&surface_from=&surface_to=&floor_from=&floor_to=&nomer=&keyword=&city_id=1&search_city=&a_id[]=5873&a_id[]=5861&a_id[]=5862&a_id[]=5863&a_id[]=5864&a_id[]=5865&a_id[]=5866&a_id[]=5880&a_id[]=9&ads_type=all&order=1&show_all=on&page={0}
        max_pages_match: normalize-space((//div[@class="pg"]/ul/li/a)[position()=last()]/strong/text())
        list_items_match: //form[@name="search"]/div[@class="tabc"]/div[contains(@class,"item")]
        item_attributes:
            - name: id
              match: div/a[@class="price"]/@href
            - name: image
              match: div/a/div/img[@class="thumb nop"]/@src
              prefix: http://www.imoti.net/
            - name: description
              match: div/p[@class="left"]//text()
            - name: price
              match: div/a[@class="price"]//text()
            - name: area
              match: div/h2//text()
            - name: link
              match: div/a[@class="price"]/@href
              prefix: http://www.imoti.net/
    Тристаен @ imoti.net:
        enabled: True
        search_url: http://www.imoti.net/search/results/?personal=&ad_type_id=3&save_search=1&search_form=prodajbi&lang=bg&x=65&y=16&building_type_id[]=9&price_from=&price_to=600&currency_id=2&price_kv_from=&price_kv_to=&currency_kv_id=4&surface_from=&surface_to=&floor_from=&floor_to=&nomer=&keyword=&city_id=1&search_city=&a_id[]=5873&a_id[]=5861&a_id[]=5862&a_id[]=5863&a_id[]=5864&a_id[]=5865&a_id[]=5866&a_id[]=5880&a_id[]=9&extra_12=12&ads_type=all&order=1&show_all=on&page={0}
        max_pages_match: normalize-space((//div[@class="pg"]/ul/li/a)[position()=last()]/strong/text())
        list_items_match: //form[@name="search"]/div[@class="tabc"]/div[contains(@class,"item")]
        item_attributes:
            - name: id
              match: div/a[@class="price"]/@href
            - name: image
              match: div/a/div/img[@class="thumb nop"]/@src
              prefix: http://www.imoti.net/
            - name: description
              match: div/p[@class="left"]//text()
            - name: price
              match: div/a[@class="price"]//text()
            - name: area
              match: div/h2//text()
            - name: link
              match: div/a[@class="price"]/@href
              prefix: http://www.imoti.net/
template_config:
  description: |
    Обяви в Център, Лозенец, Студентски, Младостите и Дървеница за:
      <strong>Едностаен до 350лв</strong><br>
      <strong>Тристаен до 600лв</strong><br>
