extend: secrets.yaml

name: Properties_monitor_gm
database: properties_gm.db
subject: Имоти в Горна Малина
send_deletes: False
enabled: False
headers:
    User-Agent: Mozilla/5.0
sites:
    Къщи@imot.bg:
        enabled: True
        search_urls:
            - site: Горна Малина
              url: http://www.imot.bg/pcgi/imot.cgi?act=3&rub=1&rub_pub_save=1&topmenu=2&actions=1&f0=77.70.77.231&f1={0}&f2=&f3=&f4=1&f7=10%7E&f28=&f29=300000&f43=&f44=&f30=EUR&f26=200&f27=&f41=1&f31=&f32=&f38=%EE%E1%EB%E0%F1%F2+%D1%EE%F4%E8%FF&ri=%F1.+%C3%EE%F0%ED%E0+%CC%E0%EB%E8%ED%E0&f42=&f39=&f40=%F1.+%C3%EE%F0%ED%E0+%CC%E0%EB%E8%ED%E0%2B&fe3=&fe4=&f45=&f46=&f51=&f52=&f33=&f34=&f35=&f36=&f37=&fe2=1
        max_pages_match: substring-after((//table/tr/td/table/tr/td/span[@class="pageNumbersInfo"])[1]//text(), "от ")
        list_items_match: //table[@width="660"][tr/td/div[@class="price"]]
        item_attributes:
            - name: id
              match: tr/td/div[@class="price"]/a/@id
            - name: image
              match: (tr/td/table/tr/td/a[@class="photoLink"]/img/@src)[1]
              prefix: "http:"
            - name: description
              match: (tr/td[@width="520"])//text()
            - name: price
              match: tr/td/div[@class="price"]//text()[1]
              post_processor: price_extractor
            - name: area
              match: tr/td/a[@class="lnk2"]//text()
            - name: link
              match: tr/td/a[@class="lnk2"]/@href
              prefix: "http:"
    Къщи@imoti.net:
        enabled: True
        search_urls:
            - site: Горна Малина
              url: https://www.imoti.net/bg/obiavi/rezultati/prodava/sofia-oblast-s-gorna-malina/kashta-vila/iy82Fs?page={0}
        max_pages_match: normalize-space(/html/body/div/main/div/div/nav/a[position()=last()-1]/text())
        list_items_match: //ul[@class="list-view real-estates"]/li
        item_attributes:
            - name: id
              match: a/@href
            - name: image
              match: figure/div/div/a/img/@src
              prefix: http://www.imoti.net
            - name: description
              match: div[@class="real-estate-text"]/p/text()
            - name: price
              match: (div/header/strong|div/header/div/strong)/text()[normalize-space()]
              post_processor: price_extractor
            - name: area
              match: div/header/div/span[@class="location"]/text()
            - name: link
              match: a/@href
              prefix: http://www.imoti.net
    Къщи@imoti.info:
        enabled: True
        search_urls:
            - site: Горна Малина
              url: http://www.imoti.info/pcgi/info.cgi?act=2&pn=1&f38=%EE%E1%EB%E0%F1%F2+%D1%EE%F4%E8%FF&f42=&f39=&f40=%F1.+%C3%EE%F0%ED%E0+%CC%E0%EB%E8%ED%E0%2B&f16=1&f17=1&f28=&f29=300000&f30=EUR&f26=200&f27=&f31=&f32=&f33=&f34=&f35=&f36=&f37=&f41=1&f1={0}
        max_pages_match: //a[@class="pageNumbers"][position()=last()]/text()
        list_items_match: //table[@style="margin-bottom:0px; border-top:#CCC 1px solid;"]
        item_attributes:
            - name: id
              match: tr/td/table/tr/td/a[@class="photoLink"]/@href
            - name: price
              match: tr/td/div[@class="price"]/text()
              post_processor: price_extractor
            - name: link
              match: tr/td/table/tr/td/a[@class="photoLink"]/@href
              prefix: http://www.imoti.info
            - name: image
              match: tr/td/table/tr/td/a[@class="photoLink"]/img/@src
            - name: description
              match: tr[3]/td/text()[normalize-space()]
            - name: area
              match: tr[3]/td/b/text()
    Къщи@holmes.bg:
        enabled: True
        search_urls:
            - site: Горна Малина
              url: http://www.holmes.bg/pcgi/home.cgi?act=2&pn=1&f1=1&f38=%EE%E1%EB%E0%F1%F2+%D1%EE%F4%E8%FF&ri=%F1.+%C3%EE%F0%ED%E0+%CC%E0%EB%E8%ED%E0&f42=&f39=&f40=%F1.+%C3%EE%F0%ED%E0+%CC%E0%EB%E8%ED%E0%2B&f16=1&f17=1&f28=&f29=300000&f30=EUR&f26=200&f27=&f31=&f32=&f33=&f34=&f35=&f36=&f37=&f41=1f1={0}
        max_pages_match: ((//table[@cellspacing=3]/tr/td/a)[position()=last()-1])/text()[normalize-space()]
        list_items_match: //table[@width=956 and not(@style)][position()>1]
        item_attributes:
            - name: id
              match: tr[1]/td[1]/table/tr/td/a/@href
            - name: image
              match: tr[1]/td[1]/table/tr/td/a/img/@src
            - name: description
              match: tr[2]/td[1]/table/tr[1]/td[1]//text()
            - name: price
              match: tr[1]/td[3]//text()
              post_processor: price_extractor
            - name: area
              match: tr[1]/td[2]//text()
            - name: link
              match: tr[1]/td[1]/table/tr/td/a/@href
              prefix: http://www.holmes.bg
template: config/templates/properties.html
template_config:
  name: ""
  description: Обяви за къщи около София