extend: secrets.yaml

name: Properties_monitor
database: properties.db
subject: Имоти около София v2
send_deletes: False
headers:
    User-Agent: Mozilla/5.0
sites:
    Къщи@imot.bg:
        enabled: True
        search_urls:
            - site: Бункера, Малинова Долина, Герена, Симеоново, Драгалевци, Могилите, Милкова Кория, Орехите, Киноцентъра, Бояна
              url: http://www.imot.bg/pcgi/imot.cgi?act=3&rub=1&rub_pub_save=1&topmenu=2&actions=1&f0=77.70.77.231&f1={0}&f2=&f3=&f4=1&f7=10%7E11%7E&f28=&f29=260000&f43=&f44=&f30=EUR&f26=205&f27=&f41=1&f31=&f32=&f38=%E3%F0%E0%E4+%D1%EE%F4%E8%FF&f42=&f39=&f40=%E2.%E7.%C1%F3%ED%EA%E5%F0%E0%2B%E2.%E7.%CC%E0%EB%E8%ED%EE%E2%E0+%E4%EE%EB%E8%ED%E0+-+%C3%E5%F0%E5%ED%E0%2B%E2.%E7.%CC%E0%EB%E8%ED%EE%E2%E0+%E4%EE%EB%E8%ED%E0%2B%D1%E8%EC%E5%EE%ED%EE%E2%EE%2B%E2.%E7.%D1%E8%EC%E5%EE%ED%EE%E2%EE+-+%C4%F0%E0%E3%E0%EB%E5%E2%F6%E8%2B%E2.%E7.%CC%EE%E3%E8%EB%E0%F2%E0%2B%E2.%E7.%CC%E8%EB%EA%EE%E2%E0+%EA%EE%F0%E8%FF%2B%EC-%F2+%CE%F0%E5%F5%E8%F2%E5%2B%C4%F0%E0%E3%E0%EB%E5%E2%F6%E8%2B%E2.%E7.%C4%F0%E0%E3%E0%EB%E5%E2%F6%E8+%EB%E8%F4%F2%E0%2B%EC-%F2+%C4%E5%F2%F1%EA%E8+%E3%F0%E0%E4%2B%E2.%E7.%CA%E8%ED%EE%F6%E5%ED%F2%FA%F0%E0%2B%E2.%E7.%C3%E0%E1%E0%F0%EE+-+%C0%E7%EC%E0%F2%E0%2B%EC-%F2+%CA%E8%ED%EE%F6%E5%ED%F2%FA%F0%E0%2B%E2.%E7.%CA%E8%ED%EE%F6%E5%ED%F2%FA%F0%E0+3+%F7%E0%F1%F2%2B%E2.%E7.%C1%EE%FF%ED%E0%2B&fe3=&fe4=&f45=&f46=&f51=&f52=&f33=&f34=&f35=&f36=&f37=&fe2=1
            - site: Горни и Долни Лозен, Панчарево, Кокаляне, Бистрица, Герман
              url: http://www.imot.bg/pcgi/imot.cgi?act=3&rub=1&rub_pub_save=1&topmenu=2&actions=1&f0=77.70.77.231&f1={0}&f2=&f3=&f4=1&f7=10%7E11%7E&f28=&f29=260000&f43=&f44=&f30=EUR&f26=205&f27=&f41=1&f31=&f32=&f38=%EE%E1%EB%E0%F1%F2+%D1%EE%F4%E8%FF&ri=%F1.+%C3%E5%F0%EC%E0%ED&f42=&f39=&f40=%F1.+%C1%E8%F1%F2%F0%E8%F6%E0%2B%F1.+%CF%E0%ED%F7%E0%F0%E5%E2%EE%2B%F1.+%CA%EE%EA%E0%EB%FF%ED%E5%2B%F1.+%C4%EE%EB%ED%E8+%CB%EE%E7%E5%ED%2B%F1.+%C3%EE%F0%ED%E8+%CB%EE%E7%E5%ED%2B%F1.+%C3%E5%F0%EC%E0%ED%2B&fe3=&fe4=&f45=&f46=&f51=&f52=&f33=&f34=&f35=&f36=&f37=&fe2=1
        max_pages_match: substring-after((//table/tr/td/table/tr/td/span[@class="pageNumbersInfo"])[1]//text(), "от ")
        list_items_match: //table[@width="660"][tr/td/div[@class="price"]]
        item_attributes:
            - name: id
              match: tr/td/div[@class="price"]/a/@id
            - name: image
              match: (tr/td/table/tr/td/a[@class="photoLink"]/img/@src)[1]
              prefix: "http:"
            - name: description
              match: (tr/td[@width="520"])//text()
            - name: price
              match: tr/td/div[@class="price"]//text()[1]
              post_processor: price_extractor
            - name: area
              match: tr/td/a[@class="lnk2"]//text()
            - name: link
              match: tr/td/a[@class="lnk2"]/@href
              prefix: "http:"
    Къщи@imoti.net:
        enabled: True
        search_urls:
            - site: Горни и Долни Лозен, Панчарево, Кокаляне, Бистрица, Герман, Симеоново, Драгалевци, Бояна, Киноцентъра
              url: https://www.imoti.net/bg/obiavi/rezultati/prodava/sofia/kashta-vila/fgbAXF?page={0}
#              data: ad_type_id=2&items_per_page=10&page=2&new_buildings=0&country_id=66&world_area_id=1&second_descendant_id%5B%5D=5431&second_descendant_id%5B%5D=5749&second_descendant_id%5B%5D=5436&second_descendant_id%5B%5D=5801&second_descendant_id%5B%5D=5747&second_descendant_id%5B%5D=5800&second_descendant_id%5B%5D=5446&second_descendant_id%5B%5D=5826&second_descendant_id%5B%5D=5456&second_descendant_id%5B%5D=5803&property_type_id%5B%5D=14&property_type_id%5B%5D=25&building_type_id=&floor=&floor_top=&months_to_target_date=&price-range-from=&price-range-to=260000&price-range-currency=eur&price-sqm-range-from=&price-sqm-range-to=&price-sqm-range-currency=eur&area-range-from=205&area-range-to=&ad_id=&key-words=
#              page_arg: ?page={0}
        max_pages_match: normalize-space(/html/body/div/main/div/div/nav/a[position()=last()-1]/text())
        list_items_match: //ul[@class="list-view real-estates"]/li
        item_attributes:
            - name: id
              match: a/@href
            - name: image
              match: figure/div/div/a/img/@src
              prefix: http://www.imoti.net
            - name: description
              match: div[@class="real-estate-text"]/p/text()
            - name: price
              match: (div/header/strong|div/header/div/strong)/text()[normalize-space()]
              post_processor: price_extractor
            - name: area
              match: div/header/div/span[@class="location"]/text()
            - name: link
              match: a/@href
              prefix: http://www.imoti.net
    Къщи@imoti.info:
        enabled: True
        search_urls:
            - site: Бункера, Малинова Долина, Герена, Симеоново, Драгалевци, Могилите, Милкова Кория, Орехите, Киноцентъра, Бояна
              url: http://www.imoti.info/pcgi/info.cgi?act=2&pn=1&f38=%E3%F0%E0%E4+%D1%EE%F4%E8%FF&f42=&f39=&f40=%E2.%E7.%C1%EE%FF%ED%E0%2B%E2.%E7.%C1%F3%ED%EA%E5%F0%E0%2B%E2.%E7.%C3%E0%E1%E0%F0%EE+-+%C0%E7%EC%E0%F2%E0%2B%E2.%E7.%C4%F0%E0%E3%E0%EB%E5%E2%F6%E8+%EB%E8%F4%F2%E0%2B%E2.%E7.%CA%E8%ED%EE%F6%E5%ED%F2%FA%F0%E0%2B%E2.%E7.%CA%E8%ED%EE%F6%E5%ED%F2%FA%F0%E0+3+%F7%E0%F1%F2%2B%E2.%E7.%CC%E0%EB%E8%ED%EE%E2%E0+%E4%EE%EB%E8%ED%E0%2B%E2.%E7.%CC%E0%EB%E8%ED%EE%E2%E0+%E4%EE%EB%E8%ED%E0+-+%C3%E5%F0%E5%ED%E0%2B%E2.%E7.%CC%E8%EB%EA%EE%E2%E0+%EA%EE%F0%E8%FF%2B%E2.%E7.%CC%EE%E3%E8%EB%E0%F2%E0%2B%E2.%E7.%D1%E8%EC%E5%EE%ED%EE%E2%EE+-+%C4%F0%E0%E3%E0%EB%E5%E2%F6%E8%2B%EC-%F2+%C4%E5%F2%F1%EA%E8+%E3%F0%E0%E4%2B%EC-%F2+%CA%E8%ED%EE%F6%E5%ED%F2%FA%F0%E0%2B%EC-%F2+%CE%F0%E5%F5%E8%F2%E5%2B&f16=1&f17=1&f28=&f29=260000&f30=EUR&f26=205&f27=&f31=&f32=&f33=&f34=&f35=&f36=&f37=&f41=1&f1={0}
            - site: Горни и Долни Лозен, Панчарево, Кокаляне, Бистрица, Герман
              url: http://www.imoti.info/pcgi/info.cgi?act=2&pn=1&f38=%EE%E1%EB%E0%F1%F2+%D1%EE%F4%E8%FF&ri=%F1.+%C3%EE%F0%ED%E8+%CB%EE%E7%E5%ED&f42=&f39=&f40=%F1.+%C1%E8%F1%F2%F0%E8%F6%E0%2B%F1.+%C3%E5%F0%EC%E0%ED%2B%F1.+%CA%EE%EA%E0%EB%FF%ED%E5%2B%F1.+%CF%E0%ED%F7%E0%F0%E5%E2%EE%2B%F1.+%C4%EE%EB%ED%E8+%CB%EE%E7%E5%ED%2B%F1.+%C3%EE%F0%ED%E8+%CB%EE%E7%E5%ED%2B&f16=1&f17=1&f28=&f29=260000&f30=EUR&f26=205&f27=&f31=&f32=&f33=&f34=&f35=&f36=&f37=&f41=1&f1={0}
        max_pages_match: //a[@class="pageNumbers"][position()=last()]/text()
        list_items_match: //table[@style="margin-bottom:0px; border-top:#CCC 1px solid;"]
        item_attributes:
            - name: id
              match: tr/td/table/tr/td/a[@class="photoLink"]/@href
            - name: price
              match: tr/td/div[@class="price"]/text()
              post_processor: price_extractor
            - name: link
              match: tr/td/table/tr/td/a[@class="photoLink"]/@href
              prefix: http://www.imoti.info
            - name: image
              match: tr/td/table/tr/td/a[@class="photoLink"]/img/@src
            - name: description
              match: tr[3]/td/text()[normalize-space()]
            - name: area
              match: tr[3]/td/b/text()
    Къщи@holmes.bg:
        enabled: True
        search_urls:
            - site: Бункера, Малинова Долина, Герена, Симеоново, Драгалевци, Могилите, Милкова Кория, Орехите, Киноцентъра, Бояна
              url: http://www.holmes.bg/pcgi/home.cgi?act=2&pn=1&f1=1&f38=%E3%F0%E0%E4+%D1%EE%F4%E8%FF&f42=&f39=&f40=%E2.%E7.%C1%EE%FF%ED%E0%2B%EC-%F2+%CA%E8%ED%EE%F6%E5%ED%F2%FA%F0%E0%2B%E2.%E7.%CA%E8%ED%EE%F6%E5%ED%F2%FA%F0%E0+3+%F7%E0%F1%F2%2B%E2.%E7.%C3%E0%E1%E0%F0%EE+-+%C0%E7%EC%E0%F2%E0%2B%E2.%E7.%CA%E8%ED%EE%F6%E5%ED%F2%FA%F0%E0%2B%E2.%E7.%C4%F0%E0%E3%E0%EB%E5%E2%F6%E8+%EB%E8%F4%F2%E0%2B%EC-%F2+%CE%F0%E5%F5%E8%F2%E5%2B%E2.%E7.%CC%E8%EB%EA%EE%E2%E0+%EA%EE%F0%E8%FF%2B%E2.%E7.%D1%E8%EC%E5%EE%ED%EE%E2%EE+-+%C4%F0%E0%E3%E0%EB%E5%E2%F6%E8%2B%E2.%E7.%CC%EE%E3%E8%EB%E0%F2%E0%2B%E2.%E7.%C1%F3%ED%EA%E5%F0%E0%2B%E2.%E7.%CC%E0%EB%E8%ED%EE%E2%E0+%E4%EE%EB%E8%ED%E0+-+%C3%E5%F0%E5%ED%E0%2B%E2.%E7.%CC%E0%EB%E8%ED%EE%E2%E0+%E4%EE%EB%E8%ED%E0%2B%EC-%F2+%C4%E5%F2%F1%EA%E8+%E3%F0%E0%E4%2B&f16=1&f17=1&f28=&f29=260000&f30=EUR&f26=205&f27=&f31=&f32=&f33=&f34=&f35=&f36=&f37=&f41=1&f1={0}
            - site: Горни и Долни Лозен, Панчарево, Кокаляне, Бистрица, Герман
              url: http://www.holmes.bg/pcgi/home.cgi?act=2&pn=1&f1=1&f38=%EE%E1%EB%E0%F1%F2+%D1%EE%F4%E8%FF&ri=%F1.+%CF%E0%ED%F7%E0%F0%E5%E2%EE&f42=&f39=&f40=%F1.+%C1%E8%F1%F2%F0%E8%F6%E0%2B%F1.+%C3%EE%F0%ED%E8+%CB%EE%E7%E5%ED%2B%F1.+%C3%E5%F0%EC%E0%ED%2B%F1.+%C4%EE%EB%ED%E8+%CB%EE%E7%E5%ED%2B%F1.+%CA%EE%EA%E0%EB%FF%ED%E5%2B%F1.+%CF%E0%ED%F7%E0%F0%E5%E2%EE%2B&f16=1&f17=1&f28=&f29=260000&f30=EUR&f26=205&f27=&f31=&f32=&f33=&f34=&f35=&f36=&f37=&f41=1&f1={0}
        max_pages_match: ((//table[@cellspacing=3]/tr/td/a)[position()=last()-1])/text()[normalize-space()]
        list_items_match: //table[@width=956 and not(@style)][position()>1]
        item_attributes:
            - name: id
              match: tr[1]/td[1]/table/tr/td/a/@href
            - name: image
              match: tr[1]/td[1]/table/tr/td/a/img/@src
            - name: description
              match: tr[2]/td[1]/table/tr[1]/td[1]//text()
            - name: price
              match: tr[1]/td[3]//text()
              post_processor: price_extractor
            - name: area
              match: tr[1]/td[2]//text()
            - name: link
              match: tr[1]/td[1]/table/tr/td/a/@href
              prefix: http://www.holmes.bg
template: config/templates/properties.html
template_config:
  name: ""
  description: Обяви за къщи около София